---
# Enable Aegir to access as a remote user.

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Include OS-specific tasks.
  include: "{{ ansible_os_family }}.yml"

- name: Create stub apache.conf file
  copy:
    dest: "{{ aegir_user_home }}/config/apache.conf"
    content: ''
    owner: "{{ aegir_user_name }}"
    group: "{{ aegir_user_name }}"
    force: no

- name: Add aegir user to sudoers to reload apache
  lineinfile:
    dest: '{{ sudoers_file_path }}'
    regexp: '^{{ aegir_user_name }}'
    line: '{{ aegir_user_name }} ALL=NOPASSWD: {{ apache_control }}'
    state: present
    validate: 'visudo -cf %s'
    create: yes

- name: Test sudo apache2ctl reload access.
  become: yes
  become_user: "{{ aegir_user_name }}"
  become_method: "{{ ansible_become_method_aegir }}"
  command: "sudo {{ apache_control }} -S"
  warn: no

- name: Add aegir to apache group.
  when: aegir_user_in_web_group == 'yes'
  user:
    name: "{{ aegir_user_name }}"
    groups: "{{ apache_user }}"
    append: yes

- name: Post Install on RedHat
  include: "RedHat-post.yml"
  when: ansible_os_family == "RedHat"

- name: Post Install on Debian
  include: "Debian-post.yml"
  when: ansible_os_family == "Debian"
