#
# docker-compose.tests.yml
#
# This dockerfile is CI only. It maps the test assets folder only and adds a CI environment var.
#
version: '2.2'
services:
  devshop:
    hostname: ${DEVSHOP_SERVER_HOSTNAME:-devshop.local.computer}
    build:
      args:
      - CI=CI

    environment:
    - GITHUB_TOKEN
    - CI=CI

    volumes:
      - ./:/usr/share/devshop:delegated
      - ./.github/.test-assets:/usr/share/devshop/.github/test-assets
