
# Netlify Settings
# See https://docs.netlify.com/configure-builds/file-based-configuration/#sample-file
[build]
  # See Makefile.
  command = "make build"

[[redirects]]
  from = "/build/install.sh"
  to = "/"
  status = 200
  headers = {Content-Type = "text/plain"}
