---

- name: Include OS-specific variables.
  include_vars: "vars.{{ ansible_os_family }}.yml"

- name: Install extra packages
  apt:
    pkg: "{{ item }}"
    state: installed
    update_cache: yes
  when: ansible_os_family == "Debian"
  with_items: '{{ extra_packages }}'

- name: Install extra packages
  yum:
    name: "{{ item }}"
    state: present
  when: ansible_os_family == "RedHat"
  with_items: '{{ extra_packages }}'

- hostname: name={{ server_hostname }}

- name: Install Drush
  get_url:
    url: "https://github.com/drush-ops/drush/releases/download/{{ drush_release_version }}/drush.phar"
    dest: "{{ local_bin_path }}/drush"
    mode: 0755

- name: Detect devshop CLI
  stat:
    path: "{{ devshop_cli_path }}"
  register: cliPath

- name: Install devshop CLI if it is not present.
  when: cliPath.stat.islnk is not defined
  git:
    repo: "{{ devshop_cli_repo }}"
    version: "{{ devshop_cli_version }}"
    update: "{{ devshop_cli_update }}"
    dest: "{{ devshop_cli_path }}"

- name: Setup devshop CLI
  command: "{{ composer_path }} install"
  args:
    chdir: "{{ devshop_cli_path }}"

- name: Setup devshop CLI executable
  file:
    src: "{{ devshop_cli_path }}/bin/devshop"
    dest: "{{ local_bin_path }}/devshop"
    state: link
    force: yes

- name: Create /var/aegir/.drush
  file:
    path: "{{ aegir_user_home }}/.drush"
    owner: "{{ aegir_user_name }}"
    group: "{{ aegir_user_name }}"
    mode: 0744
    state: directory

- name: Install required drush packages.
  command: "{{ local_bin_path }}/drush dl {{ item.key }}-{{ item.value }} --destination={{ aegir_user_home }}/.drush/commands --package-handler={{ drush_dl_method }} -y"
  with_dict: "{{ devshop_drush_packages }}"
  become: yes
  become_user: "{{ aegir_user_name }}"
  become_method: "{{ ansible_become_method_aegir }}"

- name: Setup Drush Bash Enhancements
  command: "{{ local_bin_path }}/drush init --yes"
  become: yes
  become_user: "{{ aegir_user_name }}"
  become_method: "{{ ansible_become_method_aegir }}"

- name: Clear the drush cache.
  command: "{{ local_bin_path }}/drush cc drush"
  become: yes
  become_user: "{{ aegir_user_name }}"
  become_method: "{{ ansible_become_method_aegir }}"

- name: Devmaster Install Command
  debug:
    msg: "{{ devmaster_install_command }}"

- name: Install Devmaster
  become: yes
  become_user: "{{ aegir_user_name }}"
  become_method: "{{ ansible_become_method_aegir }}"
  command: "{{ devmaster_install_command }}"
  args:
    creates: "{{ aegir_user_home }}/.drush/hostmaster.alias.drushrc.php"

- name: DevShop.Support | Save License Key
  become: yes
  become_user: "{{ aegir_user_name }}"
  become_method: "{{ ansible_become_method_aegir }}"
  command: "{{ local_bin_path }}/drush @hostmaster vset devshop_support_license_key {{ devshop_support_license_key }}"
  when: devshop_support_license_key != ""

- name: DevShop.Support | Validate License Key to setup support modules.
  become: yes
  become_user: "{{ aegir_user_name }}"
  become_method: "{{ ansible_become_method_aegir }}"
  command: "{{ local_bin_path }}/drush @hostmaster hosting-devshop_support -v"
  when: devshop_support_license_key != ""

- name: Save SSH key as variable
  shell: "{{ local_bin_path }}/drush @hostmaster vset devshop_public_key \"$(cat ~/.ssh/id_rsa.pub)\" --yes"
  become: yes
  become_user: aegir
  become_method: "{{ ansible_become_method_aegir }}"

- name: Ensure privacy of SSH Keys
  file: path=/var/aegir/{{ item.path }} mode={{ item.mode }}
  with_items:
    - { path: '.ssh', mode: '0700' }
    - { path: '.ssh/id_rsa', mode: '600' }
    - { path: '.ssh/id_rsa.pub', mode: '644' }

- name: Set git user name and email
  shell: "git config --global user.email aegir@{{ server_hostname }}"
  become: yes
  become_user: "{{ aegir_user_name }}"
  become_method: "{{ ansible_become_method_aegir }}"

- name: Set git user name and email
  shell: "git config --global user.name DevShop"
  become: yes
  become_user: "{{ aegir_user_name }}"
  become_method: "{{ ansible_become_method_aegir }}"

- name: Set git user name and email
  shell: "git config --global push.default simple"
  become: yes
  become_user: "{{ aegir_user_name }}"
  become_method: "{{ ansible_become_method_aegir }}"

- name: Clear the drush cache.
  command: "{{ local_bin_path }}/drush cc drush"
  become: yes
  become_user: "{{ aegir_user_name }}"
  become_method: "{{ ansible_become_method_aegir }}"

- name: Setup Supervisor
  include: "supervisor.yml"

# CentOS started failing tests because the PHP CLI was throwing Warnings about date.timezone missing.
# @TODO: Investigate php.ini for CLI on all OS
#- name: 'RedHat: Set timezone in PHP.ini for CLI.'
#  lineinfile:
#    dest: '{{ php_cli_ini_path }}'
#    line: 'date.timezone = America/Chicago'
#  when: ansible_os_family == "RedHat"
