---
# defaults file for aegir.user
aegir_user_uid: 12345
aegir_user_name: aegir
aegir_user_home: /var/aegir
aegir_user_authorized_keys: ReplaceAtRuntime
aegir_logs_path: /var/log/aegir

# Used for the secondary install scripts for fix-perms and fix-ownership so far
aegir_hosting_version: "7.x-3.160"

# Be sure to match to opendevshop.aegir-devmaster role
local_bin_path: /usr/local/bin

# Set to "no" to prevent playbook from creating a local user.
aegir_create_user: 'yes'

# Set to "no" to prevent playbook from trying to add aegir to web server group.
aegir_user_in_web_group: 'yes'