---

# Default server hostname. Will be set if `server_hostname` var is not set.
# Used in Docker build or image build process
default_server_hostname: devshop.local.computer


# Add hosting-queue-runner to supervisor programs.
supervisor_programs:
  - name: 'hosting-queue-runner'
    # The reason we source /etc/profile here is to ensure the environment in supervisor matches the environment when using a shell instance.
    command: "/bin/bash -c 'source /etc/profile && {{ hosting_queue_runner_bin_path }}'"
    state: present

    # See https://github.com/Supervisor/supervisor/blob/master/supervisor/skel/sample.conf for options
    configuration: |
      user={{ aegir_user_name }}
      numprocs=1
      # @TODO: hosting-queue-runner script was supposed to stay running until the site was ready for the drush hosting-task command.
      startretries=100
      stdout_logfile={{ hosting_queue_runner_log_path }}
      redirect_stderr=true
      autostart=TRUE
      autorestart=TRUE
      killasgroup=true
      stopasgroup=true
      environment=PATH="$PATH:/usr/local/bin:/usr/bin:/bin:{{ devshop_cli_bin_path }}",HOME="{{ aegir_user_home }}",USER="{{ aegir_user_name }}"

  - name: 'git-remote-monitor'
    # The reason we source /etc/profile here is to ensure the environment in supervisor matches the environment when using a shell instance.
    command: "/bin/bash -c 'source /etc/profile && {{ git_remote_monitord_path }}'"
    state: present

    # See https://github.com/Supervisor/supervisor/blob/master/supervisor/skel/sample.conf for options
    configuration: |
      user={{ aegir_user_name }}
      numprocs=1
      startretries=100
      stdout_logfile={{ git_remote_monitord_logs }}
      redirect_stderr=true
      autostart=TRUE
      autorestart=TRUE
      killasgroup=true
      stopasgroup=true
      environment=PATH="$PATH:/usr/local/bin:/usr/bin:/bin:{{ devshop_cli_bin_path }}",HOME="{{ aegir_user_home }}",USER="{{ aegir_user_name }}"
