---
local_bin_path: /usr/local/sbin
apache_user: apache

# Used to inject date.timezone.
# ip_cli_ini_path: /opt/rh/php55/root/etc/php.ini

supervisor_daemon: supervisord
supervisor_hosting_queued_conf_path: /etc/supervisord.d/hosting-queue-runner.ini

__extra_packages:
  - postfix
  - sendmail
  - cronie
  - openssl
  - mod_ssl

php_mysql_package: php-mysqlnd
