---
# vars file for aegir.apache on Debian
apache_control: /usr/sbin/apachectl
apache_user: apache

php_packages:
  - php
  - php-mysqlnd
  - php-cli
  - php-gd
  - php-process
  - php-pear
  - php-xml
  - php-mbstring
