---
galaxy_info:
  author: Jon Pugh
  description: Installs a DevShop Master server
  company: ThinkDrop Inc
  min_ansible_version: 2.0
  license: GPLv2

  platforms:
    - name: EL
      versions:
        - 7
    - name: Ubuntu
      versions:
        - trusty
        - xenial

  galaxy_tags:
    - aegir
    - apache
    - devshop
    - drupal
    - hosting
    - html
    - httpd
    - opendevshop
    - web
    - webops
    - webserver

dependencies:
  - opendevshop.users
  - geerlingguy.supervisor
  - geerlingguy.mysql
  - geerlingguy.php
  - geerlingguy.composer
