---

# Override geerlingguy.mysql packages list, because his RedHat-6.yml only includes mysql and mysql-server.
mysql_supports_innodb_large_prefix: true

devshop_prerequisite_packages:
  - openssh-clients
  - pip
