---
##

language: python
python: "2.7"
install:

  # Install DevShop with the standalone installer, using local playbooks.
  # Run as actual root?  Testing to see if this is a problem.
  - sudo su - root -c "wget https://raw.githubusercontent.com/opendevshop/devshop/0.x/install.sh && bash install.sh"

script:

  # Test for DevShop
  - sudo su - aegir -c "drush @hostmaster status"
  - sudo su -c "cd /usr/share/devshop/tests && composer update"
#  - sudo su aegir -c "cd /usr/share/devshop/tests && bin/behat --profile travis"

# Notify devshop IRC chatroom.
notifications:
  irc: "chat.freenode.net#devshop"
