---
# Decide what php version to install on Redhat family systems.
# Variable only applies to CentOS! (for now?)
remi_php_repo_name: remi-php55

sudoers_file_path: /etc/sudoers
aegir_user_home: /var/aegir
aegir_user_in_web_group: 'yes'